# Generated by Django 3.2.2 on 2021-05-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
