# Generated by Django 3.2.2 on 2021-06-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210531_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remain',
            field=models.IntegerField(default=0),
        ),
    ]
