# Generated by Django 3.2.2 on 2021-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
