# Generated by Django 3.2.2 on 2021-05-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('ServerProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.provider')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerProject.serverproject')),
            ],
        ),
    ]
