# Generated by Django 3.2.2 on 2021-06-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverproject',
            name='who_create',
            field=models.IntegerField(default=0),
        ),
    ]
