# Generated by Django 3.2.2 on 2021-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerProject', '0002_serverproject_who_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverproject',
            name='lenght',
            field=models.IntegerField(default=0),
        ),
    ]
